### ISSUE TITLE
Building own ae library

### ISSUE THREAD

**Issue by d0d0** [CyberShadow/MyWormNET2#5]
Hi,

I am trying to build wormNet in docker. It works fine, server is running. But I would like to do some changes in `ae` submodule, but changes are not taken into account due to dub is fetching `ae` from repository (`dependency "ae" version="==0.0.2410"`). 

Is there any way how to build custom `ae` lib? I tried to replace that line with `sourcePaths "ae/net"` or `sourcePaths "ae` but build ends with errors like 

```
ae/ui/shell/sdl2/shell.d(19,8): Error: module `sdl` is in file 'derelict/sdl2/sdl.d' which cannot be read
```

or 

```
ae/net/ssl/openssl.d(29,8): Error: module `ssl` is in file 'deimos/openssl/ssl.d' which cannot be read
```
when adding `ae/net` path

**Comment by d0d0** [comment]
Nevermind, after a while I found solution. I will leave it here, for future generations :)

1. removed `dub.sdl` file
2. `mv dub.selections.json dub.json`
3. replaced content of `dub.json` with
```json
{
  "name": "mywormnet2",
  "sourceFiles": [
    "common.d",
    "http.d",
    "irc.d",
    "mywormnet2.d"
  ],
  "targetType": "executable",
  "dependencies": {
    "ae": {
      "path": "./ae"
    }
  }
}
```

**Comment by CyberShadow** [comment]
Yes, or you can change `dependency "ae" version="==0.0.2410"` to `dependency "ae" version="*" path="where/you/cloned/ae"` in `dub.sdl`, or you can use `dub add-local`.
