### ISSUE TITLE
Compiling MyWormNET2

### ISSUE THREAD

**Issue by geckotdf** [CyberShadow/MyWormNET2#6]
Hi,
Im having a issue compiling MyWormNET2
I have Visual Studio 2022 installed, then I download and install [DMD 2.106.1](https://dlang.org/download.html#dmd)
Via CMD get the source: `dub fetch mywormnet2` 
But when I try to build the binary:

`dub build mywormnet2`

Get this error:

![image](https://github.com/CyberShadow/MyWormNET2/assets/30639137/a4ad1a4d-553d-405a-98a0-2cdbb6134e93)

Not sure if is because, something is missing or it's not compatible to the compiler.

Thanks!

**Comment by CyberShadow** [comment]
Hi, it looks like you have a very old checkout of the code. This repository doesn't use that ae version [since 2019](https://github.com/cybershadow/MyWormNET2/commit/b15e8011243b3c971f7955469f52a7532be2fc83).

Please clone again and try again.

**Comment by CyberShadow** [comment]
Oh, I see now you're using `dub fetch`.

**Comment by CyberShadow** [comment]
Tag pushed and Dub registry updated.

**Comment by geckotdf** [comment]
Hi @CyberShadow Thank you for the high speed! try it again and now have this message:

![image](https://github.com/CyberShadow/MyWormNET2/assets/30639137/83ef3fe8-b65a-48d7-a9b3-faf57e89c056)

Say something about bidirectional characters, not sure what that mean.

**Comment by CyberShadow** [comment]
Oof, you will need to use an older D version to get around that.

**Comment by geckotdf** [comment]
Perfect, some version you remember probably it's compatible, or some year? 
Will try to find and Archive and install some version from 4 years ago more or less the time of this app.

**Comment by CyberShadow** [comment]
Should work with 2.099.1: https://downloads.dlang.org/releases/2.x/2.099.1/

**Comment by geckotdf** [comment]
Perfect, I think It works OK
See a lot of "Deprecation" warnings like this, but probably it's because the AE

![image](https://github.com/CyberShadow/MyWormNET2/assets/30639137/d978d377-0461-4a72-8001-a04714a8b046)


At the end say `Linking...` in the folder finish with this:

![image](https://github.com/CyberShadow/MyWormNET2/assets/30639137/6afe728c-8f80-4759-ba6b-f82a1e34fb11)

Build the .ini file and run it and... so far so good I think:

![image](https://github.com/CyberShadow/MyWormNET2/assets/30639137/e7d8d8f7-9046-4761-91a6-98c292544848)

Thanks @CyberShadow !!

**Comment by geckotdf** [comment]
I think this will not be update for a long time, so to avoid any issues for Windows or compiling people I left here the folder with the .exe file

[mywormnet2.zip](https://github.com/CyberShadow/MyWormNET2/files/13963476/mywormnet2.zip)
