### ISSUE TITLE
Not a Issue: General Consulting

### ISSUE THREAD

**Issue by geckotdf** [CyberShadow/MyWormNET2#7]
Hi,
MyWormNET2, have some kind of players account query? or some way to show how many users are connected?
I was trying to use the:

`GameList.asp?Channel=PartyTime`

But show the created games, I'm not sure if is possible to show the connected players in general.
I try with a IRC Client connect to the server and then to a channel for example: #PartyTime
and then use the command `/USERS #PartyTime` and get the users, but Im not sure if there's any more simple solution.

Thanks!

**Comment by geckotdf** [comment]
Solved,
Made a Python Bot that get the users using the command /USERS in every channel.
Thanks!

**Comment by CyberShadow** [comment]
Hi, that works. It also shouldn't be difficult to add an endpoint to the HTTP side that returns the data you need. For example:

```patch
diff --git a/http.d b/http.d
index c52a641..b5a74b4 100644
--- a/http.d
+++ b/http.d
@@ -31,12 +31,14 @@ import ae.net.http.responseex;
 import ae.utils.array;
 
 import common;
+import irc;
 
 alias std.string.indexOf indexOf;
 
 class WormNETHttpServer
 {
 	HttpServer server;
+	WormNETIrcServer irc;
 
 	this()
 	{
@@ -138,6 +140,9 @@ class WormNETHttpServer
 						break;
 					case "UpdatePlayerInfo.asp":
 						break;
+					case "Stats":
+						html = irc.nicknames.length.to!string;
+						break;
 					default:
 						return conn.sendResponse(response.writeError(HttpStatusCode.NotFound));
 				}
diff --git a/mywormnet2.d b/mywormnet2.d
index 913e44e..d554b8e 100644
--- a/mywormnet2.d
+++ b/mywormnet2.d
@@ -47,6 +47,7 @@ class WormNETServer
 		irc.listen(configuration.irc.port, configuration.irc.address);
 
 		http.server.log = log;
+		http.irc = irc;
 		http.server.listen(configuration.http.port, configuration.http.address);
 	}
 }
```
