### ISSUE TITLE
Could not get checksum 1 on drive.: No such file or directory

### ISSUE THREAD

**Issue by videogamesmusix-github** [CyberShadow/MyWormNET2#8]
Hello!

I'm using Worms Armageddon 3.0 with Silkworm 4.12a on Windows 10 and local games runs perfectly.

I got the message "ERROR: Could not get checksum 1 on drive.: No such file or directory" twice when trying to join a hosted game in MyWormnet2, and can't join. 

When i try on local network, i get the same error once, but can join and play with no problems.

Please help me to fix this error.

Greetings and thank you for all your work in the game!!!

**Comment by CyberShadow** [comment]
Hi,

I don't think this is related to the WormNET software, but...

> I'm using Worms Armageddon 3.0 with Silkworm 4.12a on Windows 10

Which edition of the game is this?

Are you using a physical CD?

> and local games runs perfectly.

What about LAN games?

(You could try something like Hamachi to create a LAN between Internet-connected computers.)

**Comment by videogamesmusix-github** [comment]
Thank you for you quick reply!

I'm not sure what exact version is or how to check, i have an ISO image mounted. The game was patched with official WApatch 3.0.

LAN games works perfectly through TCP/IP, but only in local network ( version 3.0 have no option to type an IP address).

I know i can try HAMACHI (vpn.net now) but it is very difficult to install by my friends and i'm worry about network security issues.

**Comment by CyberShadow** [comment]
I don't think an ISO image will be enough for the copy protection. You'll need an original CD or a disk image that contains the additional information needed by the copy protection system. (This information is not possible to record in the ISO disk image format.)

**Comment by videogamesmusix-github** [comment]
Thank you again for your help! 

I will try to buy and original CD copy.

Last question, which is the format that can contain this info to avoid using the CD (actual PCs have not CD-ROM)

**Comment by CyberShadow** [comment]
It's been a while but I think the CloneCD software could create a copy of an original disk that it was then possible to mount using that software. Not sure if that can still be used today.

https://worms2d.info/Running_WA_without_the_CD#CloneCD
